### ISSUE TITLE
Random read performance intermittently dropped for 0 to 10+ seconds

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#844] opened 2021-12-15 05:50 UTC
**Describe the bug (描述bug)**

The random read performance drops by 0 intermittently

**To Reproduce (复现方法)**
1、 randwrite  1  50G file
2、echo 3 > /proc/sys/vm/drop_caches
3、randread 1 50G file
[global]
rw=randread
direct=1
numjobs=1
ioengine=libaio
bsrange=4k-4k
group_reporting
size=10G
fallocate=none

[disk01]
filename=/home/nbs/failover/test2/1.txt
3、
![image](https://user-images.githubusercontent.com/67582932/146130822-8c46f508-db99-4bee-bae2-aa3f502b936f.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by baijiaruo** [comment] 2021-12-16 03:02
This problem is because the inode is too large and the update inode time is too long, which leads to the inode lock holding time for too long。
Will be resolved by splitting inode metadata in subsequent versions

**Comment by baijiaruo** [comment] 2021-12-20 01:55
This problem is caused by too slow updateInode and will be resolved in subsequent versions

**Closed** 2022-01-24 07:21 UTC
Labels: bug, need test
